"""The READMEs and the website are generated by tools/build_docs.py; keep them in sync and free of dead links."""
import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import build_docs  # noqa: E402

READMES = ["README.md", "README.zh-Hant.md", "README.ja.md", "README.fr.md", "README.zh-CN.md"]


def headings(text):
    in_code, out = False, set()
    for line in text.splitlines():
        if line.startswith("```"):
            in_code = not in_code
        m = None if in_code else re.match(r"#{1,6} (.*)", line)
        if m:
            out.add(build_docs.slug(m.group(1)))
    return out


class GeneratedDocs(unittest.TestCase):
    def test_generated_files_are_current(self):
        stale = build_docs.stale()
        self.assertEqual(stale, [], "run `python3 tools/build_docs.py` and commit the result: " + ", ".join(stale))

    def test_all_languages_define_the_same_content(self):
        build_docs.check_content()      # raises SystemExit with a message if a language is missing keys or list items

    def test_readme_links_images_and_anchors_resolve(self):
        problems = []
        for name in READMES:
            text = (ROOT / name).read_text(encoding="utf-8")
            targets = re.findall(r"\]\(([^)\s]+)\)", text) + re.findall(r'(?:src|href)="([^"]+)"', text)
            anchors = headings(text)
            for t in targets:
                if t.startswith(("http://", "https://", "mailto:")):
                    continue
                if t.startswith("#"):
                    if t[1:] not in anchors:
                        problems.append(f"{name}: missing anchor {t}")
                elif not (ROOT / t.split("#")[0]).exists():
                    problems.append(f"{name}: missing file {t}")
        self.assertEqual(problems, [])

    def test_every_language_readme_links_to_all_the_others(self):
        for lang, name in build_docs.README.items():
            text = (ROOT / name).read_text(encoding="utf-8")
            for other, other_name in build_docs.README.items():
                if other != lang:
                    self.assertIn(f"]({other_name})", text, f"{name} does not link to {other_name}")

    def test_the_install_prompt_is_the_same_command_in_every_language(self):
        for lang, name in build_docs.README.items():
            text = (ROOT / name).read_text(encoding="utf-8")
            self.assertEqual(text.count("raw.githubusercontent.com/imoneys10k/schwab-table/main/install.sh"), 2, name)  # prompt + own command
            self.assertIn("Render OK", text)


if __name__ == "__main__":
    unittest.main()
